services:
  gonamer-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: gonamer:latest
    container_name: gonamer-docker
    volumes:
      - "/your_media_path/:/media" # Put your media path here
      - "./config.yml:/app/config.yml"
    user: "0:0"